using System.Numerics;
using Content.Shared._CitadelStation.Painting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CitadelStation.Painting.UI;

[GenerateTypedNameReferences]
public sealed partial class CanvasWindow : DefaultWindow
{
    private const string NoFrameId = "";
    private const int MinBrushSize = 1;
    private const int MaxBrushSize = 60;

    private static readonly Color[] Palette =
    [
        Color.Black, Color.White, Color.Red, Color.Orange,
        Color.Yellow, Color.Lime, Color.Green, Color.Cyan,
        Color.Blue, Color.Purple, Color.Magenta, Color.Pink,
        Color.Brown, Color.Gray, Color.Transparent, new Color(0.9f, 0.8f, 0.6f)
    ];

    private readonly List<string> _frameIds = [];
    private bool _dirty;
    private bool _canEdit = true;
    private bool _pixelsLoaded;
    private bool _updatingUi;

    public event Action<List<CanvasLayerData>, int>? OnLayersChanged;
    public event Action<int>? OnSizeChanged;
    public event Action<string?>? OnFrameSelected;
    public event Action<string>? OnTitleChanged;
    public event Action<bool, string>? OnLockRequested;

    public CanvasWindow()
    {
        RobustXamlLoader.Load(this);

        BrushButton.OnPressed += _ => SetTool(CanvasTool.Brush);
        EraserButton.OnPressed += _ => SetTool(CanvasTool.Eraser);
        FillButton.OnPressed += _ => SetTool(CanvasTool.Fill);
        EyedropperButton.OnPressed += _ => SetTool(CanvasTool.Eyedropper);

        ZoomSlider.OnValueChanged += args =>
        {
            DrawArea.SetZoom(args.Value);
            ZoomValueLabel.Text = $"{(int)MathF.Round(args.Value * 100)}%";
        };
        DrawArea.SetZoom(ZoomSlider.Value);
        ZoomValueLabel.Text = $"{(int)MathF.Round(ZoomSlider.Value * 100)}%";

        BrushSizeSlider.OnValueChanged += args =>
        {
            if (_updatingUi)
                return;
            SetBrushSize((int)MathF.Round(args.Value), syncSlider: false);
        };
        BrushSizeEdit.OnTextEntered += _ => ApplyBrushSizeFromEdit();
        BrushSizeEdit.OnFocusExit += _ => ApplyBrushSizeFromEdit();
        SetBrushSize(1);

        Res64Button.OnPressed += _ => RequestSize(64);
        Res128Button.OnPressed += _ => RequestSize(128);
        Res256Button.OnPressed += _ => RequestSize(256);

        ColorPicker.OnColorChanged += color => DrawArea.BrushColor = color;
        DrawArea.ColorPicked += color =>
        {
            ColorPicker.Color = color;
            DrawArea.BrushColor = color;
        };
        DrawArea.PixelsModified += () => _dirty = true;

        foreach (var color in Palette)
        {
            var swatch = new Button
            {
                MinSize = new Vector2(24, 24),
                MaxSize = new Vector2(24, 24),
                ModulateSelfOverride = color.A < 0.01f ? Color.White : color,
                ToolTip = color.A < 0.01f ? "Transparent" : color.ToHex()
            };
            var captured = color;
            swatch.OnPressed += _ =>
            {
                ColorPicker.Color = captured;
                DrawArea.BrushColor = captured;
            };
            PaletteGrid.AddChild(swatch);
        }

        FrameOption.OnItemSelected += args => FrameOption.SelectId(args.Id);
        LayerOption.OnItemSelected += args =>
        {
            LayerOption.SelectId(args.Id);
            DrawArea.SetActiveLayer(args.Id);
            RefreshLayerControls();
        };

        AddLayerButton.OnPressed += _ =>
        {
            if (!DrawArea.TryAddLayer(Loc.GetString("canvas-layer-default-name", ("n", DrawArea.LayerCount + 1))))
                return;
            _dirty = true;
            RebuildLayerOption();
        };

        RemoveLayerButton.OnPressed += _ =>
        {
            if (!DrawArea.TryRemoveActiveLayer())
                return;
            _dirty = true;
            RebuildLayerOption();
        };

        LayerVisibleCheck.OnToggled += args =>
        {
            if (_updatingUi)
                return;
            DrawArea.SetLayerVisible(DrawArea.ActiveLayer, args.Pressed);
            _dirty = true;
        };

        LayerOpacitySlider.OnValueChanged += args =>
        {
            if (_updatingUi)
                return;
            DrawArea.SetLayerOpacity(DrawArea.ActiveLayer, args.Value);
            _dirty = true;
        };

        ApplyFrameButton.OnPressed += _ =>
        {
            FlushLayers();
            if (FrameOption.SelectedId < 0 || FrameOption.SelectedId >= _frameIds.Count)
                return;
            var frameId = _frameIds[FrameOption.SelectedId];
            OnFrameSelected?.Invoke(string.IsNullOrEmpty(frameId) ? null : frameId);
        };

        ApplyTitleButton.OnPressed += _ =>
        {
            FlushLayers();
            OnTitleChanged?.Invoke(TitleEdit.Text);
        };

        LockButton.OnPressed += _ =>
        {
            FlushLayers();
            OnLockRequested?.Invoke(SignCheck.Pressed, TitleEdit.Text);
        };

        SaveButton.OnPressed += _ => FlushLayers();
    }

    public void PopulateFrames(IEnumerable<PaintingFramePrototype> frames)
    {
        FrameOption.Clear();
        _frameIds.Clear();
        FrameOption.AddItem(Loc.GetString("canvas-frame-none"), 0);
        _frameIds.Add(NoFrameId);

        var i = 1;
        foreach (var frame in frames)
        {
            FrameOption.AddItem(Loc.GetString(frame.Name), i);
            _frameIds.Add(frame.ID);
            i++;
        }

        FrameOption.SelectId(0);
    }

    public void UpdateState(CanvasBoundUserInterfaceState state)
    {
        _canEdit = state.CanEdit;
        DrawArea.ReadOnly = !state.CanEdit;

        if (!_pixelsLoaded || !_dirty)
        {
            DrawArea.LoadFromState(state.Size, state.Layers, state.ActiveLayer);
            _pixelsLoaded = true;
            _dirty = false;
            RebuildLayerOption();
        }

        SetResolutionButtons(state.Size);

        TitleEdit.Text = state.Title;
        TitleEdit.Editable = state.CanEdit;
        SignatureLabel.Text = string.IsNullOrEmpty(state.Signature)
            ? string.Empty
            : Loc.GetString("canvas-signature-display", ("author", state.Signature));

        SetEditEnabled(state.CanEdit, state.Locked);

        var frameKey = state.FrameId ?? NoFrameId;
        var idx = _frameIds.IndexOf(frameKey);
        FrameOption.SelectId(idx >= 0 ? idx : 0);

        StatusLabel.Text = state.Locked
            ? Loc.GetString("canvas-status-locked")
            : state.CanEdit
                ? Loc.GetString("canvas-status-editing", ("size", state.Size))
                : Loc.GetString("canvas-status-readonly");
    }

    public void FlushLayers()
    {
        if (!_canEdit || !_dirty)
            return;

        OnLayersChanged?.Invoke(DrawArea.ExportLayers(), DrawArea.ActiveLayer);
        _dirty = false;
    }

    private void RequestSize(int size)
    {
        if (!_canEdit)
            return;

        FlushLayers();
        OnSizeChanged?.Invoke(size);
        SetResolutionButtons(size);
    }

    private void SetResolutionButtons(int size)
    {
        Res64Button.Pressed = size == 64;
        Res128Button.Pressed = size == 128;
        Res256Button.Pressed = size == 256;
    }

    private void RebuildLayerOption()
    {
        _updatingUi = true;
        LayerOption.Clear();
        var meta = DrawArea.GetLayerMeta();
        for (var i = 0; i < meta.Count; i++)
            LayerOption.AddItem($"{i + 1}. {meta[i].Name}", i);

        LayerOption.SelectId(DrawArea.ActiveLayer);
        RefreshLayerControls();
        _updatingUi = false;
    }

    private void RefreshLayerControls()
    {
        _updatingUi = true;
        var meta = DrawArea.GetLayerMeta();
        if (DrawArea.ActiveLayer < 0 || DrawArea.ActiveLayer >= meta.Count)
        {
            _updatingUi = false;
            return;
        }

        var layer = meta[DrawArea.ActiveLayer];
        LayerVisibleCheck.Pressed = layer.Visible;
        LayerOpacitySlider.Value = layer.Opacity;
        _updatingUi = false;
    }

    private void SetEditEnabled(bool canEdit, bool locked)
    {
        ApplyFrameButton.Disabled = !canEdit;
        ApplyTitleButton.Disabled = !canEdit;
        LockButton.Disabled = !canEdit || locked;
        SignCheck.Disabled = !canEdit || locked;
        SaveButton.Disabled = !canEdit;
        FrameOption.Disabled = !canEdit;
        BrushButton.Disabled = !canEdit;
        EraserButton.Disabled = !canEdit;
        FillButton.Disabled = !canEdit;
        EyedropperButton.Disabled = !canEdit;
        BrushSizeSlider.Disabled = !canEdit;
        BrushSizeEdit.Editable = canEdit;
        Res64Button.Disabled = !canEdit;
        Res128Button.Disabled = !canEdit;
        Res256Button.Disabled = !canEdit;
        AddLayerButton.Disabled = !canEdit;
        RemoveLayerButton.Disabled = !canEdit;
        LayerOption.Disabled = !canEdit;
        LayerVisibleCheck.Disabled = !canEdit;
        LayerOpacitySlider.Disabled = !canEdit;
        ColorPicker.Visible = canEdit;
    }

    private void SetTool(CanvasTool tool)
    {
        DrawArea.Tool = tool;
        BrushButton.Pressed = tool == CanvasTool.Brush;
        EraserButton.Pressed = tool == CanvasTool.Eraser;
        FillButton.Pressed = tool == CanvasTool.Fill;
        EyedropperButton.Pressed = tool == CanvasTool.Eyedropper;
    }

    private void SetBrushSize(int size, bool syncSlider = true)
    {
        size = Math.Clamp(size, MinBrushSize, MaxBrushSize);
        DrawArea.BrushSize = size;

        _updatingUi = true;
        if (syncSlider)
            BrushSizeSlider.Value = size;
        BrushSizeEdit.Text = size.ToString();
        _updatingUi = false;
    }

    private void ApplyBrushSizeFromEdit()
    {
        if (!int.TryParse(BrushSizeEdit.Text, out var size))
        {
            BrushSizeEdit.Text = DrawArea.BrushSize.ToString();
            return;
        }

        SetBrushSize(size);
    }
}
