using Content.Shared._CitadelStation.Painting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CitadelStation.Painting.UI;

[GenerateTypedNameReferences]
public sealed partial class EaselWindow : DefaultWindow
{
    public event Action<int>? OnSelectSlot;
    public event Action<int>? OnEjectSlot;
    public event Action<int>? OnOpenCanvas;

    public EaselWindow()
    {
        RobustXamlLoader.Load(this);

        SelectButton.OnPressed += _ =>
        {
            if (TryGetSelectedIndex(out var index))
                OnSelectSlot?.Invoke(index);
        };

        EditButton.OnPressed += _ =>
        {
            if (TryGetSelectedIndex(out var index))
                OnOpenCanvas?.Invoke(index);
        };

        EjectButton.OnPressed += _ =>
        {
            if (TryGetSelectedIndex(out var index))
                OnEjectSlot?.Invoke(index);
        };
    }

    public void UpdateState(EaselBoundUserInterfaceState state)
    {
        SlotList.Clear();
        for (var i = 0; i < state.SlotNames.Length; i++)
        {
            var marker = i == state.ActiveIndex ? " ★" : string.Empty;
            SlotList.AddItem($"{i + 1}. {state.SlotNames[i]}{marker}");
        }

        var hasPaintings = state.SlotNames.Length > 0;
        if (hasPaintings)
        {
            var idx = Math.Clamp(state.ActiveIndex, 0, state.SlotNames.Length - 1);
            SlotList[idx].Selected = true;
        }

        SelectButton.Disabled = !hasPaintings;
        EditButton.Disabled = !hasPaintings;
        EjectButton.Disabled = !hasPaintings;

        InfoLabel.Text = Loc.GetString("easel-info",
            ("count", state.SlotNames.Length),
            ("max", EaselComponent.MaxPaintings));
    }

    private bool TryGetSelectedIndex(out int index)
    {
        index = -1;
        foreach (var item in SlotList.GetSelected())
        {
            index = SlotList.IndexOf(item);
            return index >= 0;
        }

        // Fall back to first slot so Edit still works if selection was cleared.
        if (SlotList.Count > 0)
        {
            index = 0;
            return true;
        }

        return false;
    }
}
