using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Dialogue;

[GenerateTypedNameReferences]
public sealed partial class DialoguePanel : Control
{
    public event Action<byte>? OptionSelected;
    public event Action? LeavePressed;

    public DialoguePanel()
    {
        RobustXamlLoader.Load(this);
        LeaveButton.OnPressed += _ => LeavePressed?.Invoke();
    }

    public void SetContent(string npcName, string speech, string[] options)
    {
        NpcNameLabel.Text = npcName;
        SpeechLabel.SetMessage(string.IsNullOrWhiteSpace(speech)
            ? Loc.GetString("npc-dialogue-prompt")
            : speech);

        OptionsContainer.DisposeAllChildren();

        for (byte i = 0; i < options.Length; i++)
        {
            var index = i;
            var button = new Button
            {
                Text = options[i],
                MinWidth = 100,
            };
            button.OnPressed += _ => OptionSelected?.Invoke(index);
            OptionsContainer.AddChild(button);
        }
    }
}
