using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared._CitadelStation.HumanoidGenetics.UI;
using Content.Shared._CitadelStation.HumanoidGenetics.Components;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared.Humanoid;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._CitadelStation.HumanoidGenetics.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneticPod : FancyWindow
{

    private readonly IEntityManager _entityManager;

    private ISawmill _saw = default!;

    public GeneticPod()
    {
        _saw = Logger.GetSawmill("genetic_client");
        _entityManager = IoCManager.Resolve<IEntityManager>();
        RobustXamlLoader.Load(this);
    }

    private void AddMutationSelectionBox(BoxContainer target, MutationClass mutation) {

        var MutationBox = new BoxContainer(){
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Stretch,
            MinSize = new System.Numerics.Vector2(5,50)
        };

        MutationBox.AddChild(new Label(){
            Text = mutation.MutationProto.ToString(),
            HorizontalAlignment = HAlignment.Stretch
        });
        MutationBox.AddChild(new Button(){
            Text = "X",
            HorizontalAlignment = HAlignment.Right
        });

        target.AddChild(MutationBox);
    }

    public void UpdateState(GeneticPodBoundUserInterfaceState state)
    {

        if (state == null || state.TargetEntity == null || state.TargetEntity.HasValue == false || state.TargetEntity.Value == null)
        {
            return;
        }

        if (!_entityManager.TryGetEntity(state.TargetEntity.Value, out var _entity) || _entity is not EntityUid entity)
            return;
        PatientSprite.SetEntity(entity);

        if (!_entityManager.TryGetComponent<MetaDataComponent>(entity, out var metaData))
            return;

        if (!_entityManager.TryGetComponent<HumanoidAppearanceComponent>(entity, out var humanoidAppearance))
            return;

        PatientName.Text = metaData.EntityName;
        PatientSex.Text = humanoidAppearance.Sex.ToString();
        PatientRace.Text = humanoidAppearance.Species.ToString();

        foreach (var mutation in state.Mutations) {
            EntityMutationsList.AddChild(new MutationEntry(mutation.MutationProto.ToString(),"Some description"));
        }
    }
}
