using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CitadelStation.HumanoidGenetics.UI;

[GenerateTypedNameReferences]
public sealed partial class HumanoidGeneticSequencer : FancyWindow
{
    public HumanoidGeneticSequencer()
    {
        RobustXamlLoader.Load(this);
    }
}
