using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CitadelStation.HumanoidGenetics.UI;

[GenerateTypedNameReferences]
public sealed partial class MutationEntry : Control
{
    // A simple subclass to let us easily set the text color via code
    // since inline XAML font colors on Buttons can sometimes get overridden by SS14 themes.
    public class MutationSelectButton : Button { }

    public MutationEntry(string name, string description, string actionText = "Select")
    {
        RobustXamlLoader.Load(this);

        MutationName.Text = name;
        MutationDescription.Text = description;
        SelectButton.Text = actionText;

        // Apply the accent color to the button text
        SelectButton.FontColorOverride = Color.FromHex("#C17070");
    }

    /// <summary>
    /// Action triggered when the user clicks the Select button.
    /// </summary>
    public event Action<string>? OnMutationSelected;

    protected override void EnteredTree()
    {
        base.EnteredTree();
        SelectButton.OnPressed += OnButtonPressed;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        SelectButton.OnPressed -= OnButtonPressed;
    }

    private void OnButtonPressed(Button.ButtonEventArgs args)
    {
    }
}
