using System.Linq;
using Content.Shared.Administration;
using Content.Shared.NPC;
using Content.Shared.NPC.Dialogue;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.NpcEditor;

[GenerateTypedNameReferences]
public sealed partial class NpcEditorWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public NetEntity? TargetEntityId { get; set; }

    private NpcEditorEuiState? _state;
    private NpcPresetData _draft = NpcBehaviorWhitelist.CreateDefault();
    private readonly List<string> _gearIds = new();
    private int? _selectedPresetId;
    private string? _selectedNodeId;
    private bool _suppressNodeUi;
    private NpcAppearanceEditorWindow? _appearanceWindow;

    public event Action<NpcPresetData>? OnSpawn;
    public event Action<NetEntity, NpcPresetData>? OnApply;
    public event Action<string, NpcPresetData, int?>? OnSave;
    public event Action<int>? OnDelete;
    public event Action<NpcPresetData>? OnLoadRequested;
    public event Action? OnRefresh;

    public NpcEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("npc-editor-appearance"));
        Tabs.SetTabTitle(1, Loc.GetString("npc-editor-behavior"));
        Tabs.SetTabTitle(2, Loc.GetString("npc-editor-dialogue"));
        Tabs.SetTabTitle(3, Loc.GetString("npc-editor-faction"));
        Tabs.SetTabTitle(4, Loc.GetString("npc-editor-gear"));
        Tabs.SetTabTitle(5, Loc.GetString("npc-editor-presets"));

        PackOption.AddItem(Loc.GetString("npc-editor-pack-basic"), (int) NpcBehaviorPack.Basic);
        PackOption.AddItem(Loc.GetString("npc-editor-pack-civilian"), (int) NpcBehaviorPack.Civilian);
        PackOption.AddItem(Loc.GetString("npc-editor-pack-combat"), (int) NpcBehaviorPack.Combat);
        PackOption.OnItemSelected += args =>
        {
            PackOption.SelectId(args.Id);
            OnPackChanged((NpcBehaviorPack) args.Id);
        };

        SpeciesOption.OnItemSelected += args => SpeciesOption.SelectId(args.Id);
        HtnOption.OnItemSelected += args => HtnOption.SelectId(args.Id);
        RoleOption.OnItemSelected += args => RoleOption.SelectId(args.Id);
        DialogueTemplateOption.OnItemSelected += args => DialogueTemplateOption.SelectId(args.Id);

        GearSearch.OnTextChanged += _ => PopulateGearList(GearSearch.Text);
        GearList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is string gear)
                _draft.StartingGear = gear;
        };

        FactionList.OnItemSelected += _ => SyncFactionSelectionFromList();
        FactionList.OnItemDeselected += _ => SyncFactionSelectionFromList();

        LoadDialogueTemplateButton.OnPressed += _ => LoadSelectedDialogueTemplate();
        ClearDialogueButton.OnPressed += _ =>
        {
            _draft.CustomDialogue = null;
            _draft.DialogueTree = null;
            _selectedNodeId = null;
            RefreshDialogueEditor();
        };

        DialogueStartEdit.OnTextChanged += _ =>
        {
            EnsureCustomDialogue();
            _draft.CustomDialogue!.Start = DialogueStartEdit.Text.Trim();
        };

        DialogueNodeList.OnItemSelected += args =>
        {
            if (_suppressNodeUi)
                return;
            if (args.ItemList[args.ItemIndex].Metadata is string nodeId)
                SelectNode(nodeId);
        };

        AddNodeButton.OnPressed += _ => AddDialogueNode();
        RemoveNodeButton.OnPressed += _ => RemoveSelectedNode();

        DialogueSpeechEdit.OnTextChanged += _ =>
        {
            if (_suppressNodeUi || _selectedNodeId == null || _draft.CustomDialogue == null)
                return;
            if (!_draft.CustomDialogue.Nodes.TryGetValue(_selectedNodeId, out var node))
                return;
            node.Speech = Rope.Collapse(DialogueSpeechEdit.TextRope);
        };

        AddOptionButton.OnPressed += _ => AddDialogueOption();
        RemoveOptionButton.OnPressed += _ => RemoveSelectedOption();

        AllowWanderCheck.Pressed = _draft.AllowWander;
        UseStandPointCheck.Pressed = _draft.UseStandPoint;

        RandomAppearanceCheck.OnPressed += _ =>
        {
            _draft.RandomAppearance = RandomAppearanceCheck.Pressed;
            UpdateAppearanceStatus();
        };
        EditAppearanceButton.OnPressed += _ => OpenAppearanceEditor();
        RandomizeAppearanceButton.OnPressed += _ => RandomizeAppearanceNow();
        UpdateAppearanceStatus();

        SpawnButton.OnPressed += _ =>
        {
            CommitUiToDraft();
            OnSpawn?.Invoke(_draft);
        };
        ApplyButton.OnPressed += _ =>
        {
            if (TargetEntityId == null)
                return;
            CommitUiToDraft();
            OnApply?.Invoke(TargetEntityId.Value, _draft);
        };
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();

        SavePresetButton.OnPressed += _ =>
        {
            CommitUiToDraft();
            var name = string.IsNullOrWhiteSpace(PresetNameEdit.Text) ? _draft.DisplayName : PresetNameEdit.Text;
            OnSave?.Invoke(name.Trim(), _draft, _selectedPresetId);
        };
        DeletePresetButton.OnPressed += _ =>
        {
            if (_selectedPresetId != null)
                OnDelete?.Invoke(_selectedPresetId.Value);
        };
        LoadPresetButton.OnPressed += _ =>
        {
            if (PresetList.GetSelected().FirstOrDefault()?.Metadata is NpcPresetListEntry entry)
            {
                ApplyDraft(entry.Data);
                _selectedPresetId = entry.Id;
                PresetNameEdit.Text = entry.Name;
                OnLoadRequested?.Invoke(entry.Data);
            }
        };
        PresetList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is NpcPresetListEntry entry)
            {
                _selectedPresetId = entry.Id;
                PresetNameEdit.Text = entry.Name;
            }
        };

        ApplyDraft(_draft);
    }

    public void UpdateState(NpcEditorEuiState state)
    {
        _state = state;
        TargetEntityId = state.TargetNetEntity;
        ApplyButton.Disabled = state.TargetNetEntity == null;

        SpeciesOption.Clear();
        for (var i = 0; i < state.SpeciesIds.Count; i++)
        {
            SpeciesOption.AddItem(state.SpeciesIds[i], i);
            SpeciesOption.SetItemMetadata(i, state.SpeciesIds[i]);
        }
        SelectOptionByMetadata(SpeciesOption, _draft.Species);

        _gearIds.Clear();
        _gearIds.AddRange(state.StartingGears);
        PopulateGearList(GearSearch.Text);

        FactionList.Clear();
        foreach (var faction in state.Factions)
        {
            var item = FactionList.AddItem($"{faction.Category}: {faction.Id}");
            item.Metadata = faction.Id;
            item.Selected = _draft.Factions.Contains(faction.Id);
            if (!string.IsNullOrEmpty(faction.Description))
                item.TooltipText = faction.Description;
        }

        PresetList.Clear();
        foreach (var preset in state.Presets)
        {
            var item = PresetList.AddItem($"{preset.Name} ({preset.CreatedBy})");
            item.Metadata = preset;
        }

        RefreshDialogueTemplates(state.DialogueIds);
        RefreshHtnAndRoleOptions();
        RefreshDialogueEditor();
    }

    private void OnPackChanged(NpcBehaviorPack pack)
    {
        _draft.BehaviorPack = pack;
        _draft.HtnRoot = NpcBehaviorWhitelist.DefaultHtn[pack];
        _draft.RoleProfile = NpcBehaviorWhitelist.DefaultRoleProfile[pack];
        _draft.Factions = new List<string> { NpcBehaviorWhitelist.DefaultFaction[pack] };
        _draft.JoinSquad = pack == NpcBehaviorPack.Combat;
        RefreshHtnAndRoleOptions();
        JoinSquadCheck.Pressed = _draft.JoinSquad;

        if (_state != null)
        {
            foreach (var item in FactionList)
            {
                if (item.Metadata is string id)
                    item.Selected = _draft.Factions.Contains(id);
            }
        }
    }

    private void RefreshHtnAndRoleOptions()
    {
        var pack = _draft.BehaviorPack;
        HtnOption.Clear();
        var htns = NpcBehaviorWhitelist.HtnByPack[pack];
        for (var i = 0; i < htns.Length; i++)
        {
            HtnOption.AddItem(htns[i], i);
            HtnOption.SetItemMetadata(i, htns[i]);
        }
        SelectOptionByMetadata(HtnOption, _draft.HtnRoot);

        RoleOption.Clear();
        RoleOption.AddItem(Loc.GetString("npc-editor-role-none"), -1);
        var roles = NpcBehaviorWhitelist.RoleProfilesByPack[pack];
        for (var i = 0; i < roles.Length; i++)
        {
            RoleOption.AddItem(roles[i], i);
            RoleOption.SetItemMetadata(i + 1, roles[i]);
        }
        if (string.IsNullOrWhiteSpace(_draft.RoleProfile))
            RoleOption.TrySelectId(-1);
        else
            SelectOptionByMetadata(RoleOption, _draft.RoleProfile);
    }

    private void RefreshDialogueTemplates(List<string>? dialogueIds = null)
    {
        var ids = dialogueIds ?? _state?.DialogueIds ?? new List<string>();
        DialogueTemplateOption.Clear();
        DialogueTemplateOption.AddItem(Loc.GetString("npc-editor-dialogue-none"), -1);
        for (var i = 0; i < ids.Count; i++)
        {
            DialogueTemplateOption.AddItem(ids[i], i);
            DialogueTemplateOption.SetItemMetadata(i + 1, ids[i]);
        }

        if (string.IsNullOrWhiteSpace(_draft.DialogueTree))
            DialogueTemplateOption.TrySelectId(-1);
        else
            SelectOptionByMetadata(DialogueTemplateOption, _draft.DialogueTree);
    }

    private void LoadSelectedDialogueTemplate()
    {
        if (DialogueTemplateOption.SelectedMetadata is not string protoId)
            return;

        if (!_prototypes.TryIndex<NpcDialoguePrototype>(protoId, out var proto))
            return;

        // Editable copy of the prototype tree; plain text for in-game authoring.
        var tree = NpcDialogueTreeData.FromPrototype(proto);
        foreach (var node in tree.Nodes.Values)
        {
            node.Speech = ResolveEditorText(node.Speech);
            foreach (var option in node.Options)
                option.Text = ResolveEditorText(option.Text);
        }

        _draft.CustomDialogue = tree;
        _draft.DialogueTree = null;
        _selectedNodeId = tree.Start;
        RefreshDialogueEditor();
    }

    private static string ResolveEditorText(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return string.Empty;

        return Loc.TryGetString(text, out var localized) ? localized : text;
    }

    private void EnsureCustomDialogue()
    {
        _draft.CustomDialogue ??= new NpcDialogueTreeData
        {
            Start = "start",
            Nodes = { ["start"] = new NpcDialogueNode() },
        };
    }

    private void RefreshDialogueEditor()
    {
        _suppressNodeUi = true;
        var tree = _draft.CustomDialogue;
        DialogueStartEdit.Text = tree?.Start ?? "start";

        DialogueNodeList.Clear();
        if (tree != null)
        {
            foreach (var id in tree.Nodes.Keys.OrderBy(x => x))
            {
                var item = DialogueNodeList.AddItem(id == tree.Start ? $"{id} *" : id);
                item.Metadata = id;
                item.Selected = id == _selectedNodeId;
            }
        }

        if (_selectedNodeId != null && tree != null && tree.Nodes.TryGetValue(_selectedNodeId, out var node))
        {
            DialogueSpeechEdit.TextRope = new Rope.Leaf(node.Speech ?? string.Empty);
            DialogueOptionList.Clear();
            for (var i = 0; i < node.Options.Count; i++)
            {
                var opt = node.Options[i];
                var next = string.IsNullOrEmpty(opt.Next) ? "(end)" : opt.Next;
                var item = DialogueOptionList.AddItem($"{opt.Text} → {next}");
                item.Metadata = i;
            }
        }
        else
        {
            DialogueSpeechEdit.TextRope = new Rope.Leaf(string.Empty);
            DialogueOptionList.Clear();
        }

        _suppressNodeUi = false;
        RefreshDialogueTemplates();
    }

    private void SelectNode(string nodeId)
    {
        if (_suppressNodeUi)
            return;

        // Persist current speech before switching.
        if (_selectedNodeId != null && _draft.CustomDialogue != null &&
            _draft.CustomDialogue.Nodes.TryGetValue(_selectedNodeId, out var prev))
        {
            prev.Speech = Rope.Collapse(DialogueSpeechEdit.TextRope);
        }

        _selectedNodeId = nodeId;
        RefreshDialogueEditor();
    }

    private void AddDialogueNode()
    {
        var id = NewNodeIdEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(id))
            return;

        EnsureCustomDialogue();
        if (_draft.CustomDialogue!.Nodes.ContainsKey(id))
            return;

        _draft.CustomDialogue.Nodes[id] = new NpcDialogueNode();
        if (_draft.CustomDialogue.Nodes.Count == 1)
            _draft.CustomDialogue.Start = id;

        NewNodeIdEdit.Text = string.Empty;
        _selectedNodeId = id;
        RefreshDialogueEditor();
    }

    private void RemoveSelectedNode()
    {
        if (_selectedNodeId == null || _draft.CustomDialogue == null)
            return;

        _draft.CustomDialogue.Nodes.Remove(_selectedNodeId);
        if (_draft.CustomDialogue.Start == _selectedNodeId)
            _draft.CustomDialogue.Start = _draft.CustomDialogue.Nodes.Keys.FirstOrDefault() ?? "start";

        _selectedNodeId = _draft.CustomDialogue.Nodes.Keys.FirstOrDefault();
        if (_draft.CustomDialogue.Nodes.Count == 0)
            _draft.CustomDialogue = null;

        RefreshDialogueEditor();
    }

    private void AddDialogueOption()
    {
        if (_selectedNodeId == null)
            return;

        EnsureCustomDialogue();
        if (!_draft.CustomDialogue!.Nodes.TryGetValue(_selectedNodeId, out var node))
            return;

        var text = OptionTextEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(text))
            return;

        var nextRaw = OptionNextEdit.Text.Trim();
        node.Options.Add(new NpcDialogueOption
        {
            Text = text,
            Next = string.IsNullOrWhiteSpace(nextRaw) ? null : nextRaw,
        });

        OptionTextEdit.Text = string.Empty;
        OptionNextEdit.Text = string.Empty;
        RefreshDialogueEditor();
    }

    private void RemoveSelectedOption()
    {
        if (_selectedNodeId == null || _draft.CustomDialogue == null)
            return;
        if (!_draft.CustomDialogue.Nodes.TryGetValue(_selectedNodeId, out var node))
            return;

        var selected = DialogueOptionList.GetSelected().FirstOrDefault();
        if (selected?.Metadata is not int index || index < 0 || index >= node.Options.Count)
            return;

        node.Options.RemoveAt(index);
        RefreshDialogueEditor();
    }

    private void PopulateGearList(string? filter)
    {
        GearList.Clear();
        filter = filter?.Trim();
        foreach (var id in _gearIds)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !id.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = GearList.AddItem(id);
            item.Metadata = id;
            item.Selected = id == _draft.StartingGear;
        }
    }

    private void ApplyDraft(NpcPresetData data)
    {
        _draft = new NpcPresetData
        {
            DisplayName = data.DisplayName,
            RandomAppearance = data.RandomAppearance,
            Profile = data.Profile,
            Species = data.Species,
            BehaviorPack = data.BehaviorPack,
            HtnRoot = data.HtnRoot,
            RoleProfile = data.RoleProfile,
            StartingGear = data.StartingGear,
            Factions = new List<string>(data.Factions),
            AddFriendlyFactions = new List<string>(data.AddFriendlyFactions),
            AddHostileFactions = new List<string>(data.AddHostileFactions),
            NavClimb = data.NavClimb,
            NavInteract = data.NavInteract,
            NavPry = data.NavPry,
            NavSmash = data.NavSmash,
            JoinSquad = data.JoinSquad,
            AllowWander = data.AllowWander,
            UseStandPoint = data.UseStandPoint,
            DialogueTree = data.DialogueTree,
            CustomDialogue = data.CustomDialogue?.Clone(),
            Notes = data.Notes,
        };

        _selectedNodeId = _draft.CustomDialogue?.Nodes.Keys.FirstOrDefault();

        NameEdit.Text = _draft.DisplayName;
        RandomAppearanceCheck.Pressed = _draft.RandomAppearance;
        PackOption.SelectId((int) _draft.BehaviorPack);
        NavClimbCheck.Pressed = _draft.NavClimb;
        NavInteractCheck.Pressed = _draft.NavInteract;
        NavPryCheck.Pressed = _draft.NavPry;
        NavSmashCheck.Pressed = _draft.NavSmash;
        JoinSquadCheck.Pressed = _draft.JoinSquad;
        AllowWanderCheck.Pressed = _draft.AllowWander;
        UseStandPointCheck.Pressed = _draft.UseStandPoint;
        UpdateAppearanceStatus();
        AddHostileEdit.Text = string.Join(", ", _draft.AddHostileFactions);
        AddFriendlyEdit.Text = string.Join(", ", _draft.AddFriendlyFactions);
        SelectOptionByMetadata(SpeciesOption, _draft.Species);
        RefreshHtnAndRoleOptions();
        RefreshDialogueEditor();
        PopulateGearList(GearSearch.Text);

        if (_state != null)
        {
            foreach (var item in FactionList)
            {
                if (item.Metadata is string id)
                    item.Selected = _draft.Factions.Contains(id);
            }
        }
    }

    private void CommitUiToDraft()
    {
        _draft.DisplayName = NameEdit.Text.Trim();
        _draft.RandomAppearance = RandomAppearanceCheck.Pressed;
        _draft.BehaviorPack = (NpcBehaviorPack) PackOption.SelectedId;
        _draft.NavClimb = NavClimbCheck.Pressed;
        _draft.NavInteract = NavInteractCheck.Pressed;
        _draft.NavPry = NavPryCheck.Pressed;
        _draft.NavSmash = NavSmashCheck.Pressed;
        _draft.JoinSquad = JoinSquadCheck.Pressed;
        _draft.AllowWander = AllowWanderCheck.Pressed;
        _draft.UseStandPoint = UseStandPointCheck.Pressed;
        _draft.RandomAppearance = RandomAppearanceCheck.Pressed;

        if (SpeciesOption.SelectedMetadata is string species)
            _draft.Species = species;

        if (HtnOption.SelectedMetadata is string htn)
            _draft.HtnRoot = htn;

        _draft.RoleProfile = RoleOption.SelectedMetadata as string;

        if (_selectedNodeId != null && _draft.CustomDialogue != null &&
            _draft.CustomDialogue.Nodes.TryGetValue(_selectedNodeId, out var node))
        {
            node.Speech = Rope.Collapse(DialogueSpeechEdit.TextRope);
        }

        if (_draft.CustomDialogue != null)
        {
            _draft.CustomDialogue.Start = DialogueStartEdit.Text.Trim();
            if (_draft.CustomDialogue.Nodes.Count == 0 || !_draft.CustomDialogue.IsValid())
                _draft.CustomDialogue = null;
        }

        // Custom tree owns the dialogue; otherwise use selected prototype template.
        if (_draft.CustomDialogue != null)
            _draft.DialogueTree = null;
        else
            _draft.DialogueTree = DialogueTemplateOption.SelectedMetadata as string;

        SyncFactionSelectionFromList();
        _draft.AddHostileFactions = ParseCsv(AddHostileEdit.Text);
        _draft.AddFriendlyFactions = ParseCsv(AddFriendlyEdit.Text);
    }

    private void OpenAppearanceEditor()
    {
        if (_appearanceWindow != null)
        {
            _appearanceWindow.MoveToFront();
            return;
        }

        CommitUiToDraft();
        var species = SpeciesOption.SelectedMetadata as string ?? _draft.Species;
        var profile = _draft.Profile?.Clone() ?? HumanoidCharacterProfile.RandomWithSpecies(species);

        _appearanceWindow = new NpcAppearanceEditorWindow(profile);
        _appearanceWindow.OnConfirmed += OnAppearanceConfirmed;
        _appearanceWindow.OnClose += () =>
        {
            if (_appearanceWindow != null)
            {
                _appearanceWindow.OnConfirmed -= OnAppearanceConfirmed;
                _appearanceWindow = null;
            }
        };
        _appearanceWindow.OpenCentered();
    }

    private void OnAppearanceConfirmed(HumanoidCharacterProfile profile)
    {
        _draft.Profile = profile.Clone();
        _draft.RandomAppearance = false;
        _draft.Species = profile.Species;
        RandomAppearanceCheck.Pressed = false;
        NameEdit.Text = profile.Name;
        SelectOptionByMetadata(SpeciesOption, profile.Species);
        UpdateAppearanceStatus();
    }

    private void RandomizeAppearanceNow()
    {
        var species = SpeciesOption.SelectedMetadata as string ?? _draft.Species;
        var profile = HumanoidCharacterProfile.RandomWithSpecies(species);
        _draft.Profile = profile;
        _draft.RandomAppearance = false;
        _draft.Species = profile.Species;
        RandomAppearanceCheck.Pressed = false;
        NameEdit.Text = profile.Name;
        UpdateAppearanceStatus();
    }

    private void UpdateAppearanceStatus()
    {
        if (RandomAppearanceCheck.Pressed || _draft.Profile == null)
        {
            AppearanceStatusLabel.Text = Loc.GetString("npc-editor-appearance-status-random");
            return;
        }

        AppearanceStatusLabel.Text = Loc.GetString(
            "npc-editor-appearance-status-custom",
            ("name", _draft.Profile.Name));
    }

    private void SyncFactionSelectionFromList()
    {
        _draft.Factions = FactionList
            .Where(i => i.Selected && i.Metadata is string)
            .Select(i => (string) i.Metadata!)
            .ToList();
    }

    private static List<string> ParseCsv(string text)
    {
        var result = new List<string>();
        foreach (var part in text.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (string.IsNullOrWhiteSpace(part))
                continue;
            if (!result.Contains(part))
                result.Add(part);
        }

        return result;
    }

    private static void SelectOptionByMetadata(OptionButton button, string? text)
    {
        for (var i = 0; i < button.ItemCount; i++)
        {
            if (!Equals(button.GetItemMetadata(i), text))
                continue;
            button.Select(i);
            return;
        }
    }
}
