using System.Numerics;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        private const int ReadySegments = 16;
        private const int BrandDashSegments = 24;
        private const float NavAnimSpeed = 12f;
        private const float CounterAnimSpeed = 8f;
        private const float BadgeAnimSpeed = 10f;
        private const float SegmentAnimSpeed = 6f;
        private const float BadgeExpandedHeight = 28f;

        private static readonly Color ColorDim = Color.FromHex("#5A4020");
        private static readonly Color ColorGold = Color.FromHex("#F0A830");
        private static readonly Color ColorHover = Color.FromHex("#FFE0A0");
        private static readonly Color ColorTeal = Color.FromHex("#4AF0D0");
        private static readonly Color ColorSubDim = Color.FromHex("#1A1008");
        private static readonly Color ColorSubLit = Color.FromHex("#5A3818");
        private static readonly Color ColorAccentIdle = Color.FromHex("#2A1A08");
        private static readonly Color ColorAccentHover = Color.FromHex("#FFCC60");
        private static readonly Color ColorLineIdle = Color.FromHex("#2A1A0880");
        private static readonly Color ColorLineLit = Color.FromHex("#F0A83033");

        private readonly PanelContainer[] _readySegments = new PanelContainer[ReadySegments];
        private readonly NavItem[] _navItems = new NavItem[4];

        private NavId? _selected;
        private NavId? _hovered;
        private bool _readyTeal;
        private bool _gameStarted;

        private bool _counterWanted = true;
        private bool _badgeWanted;
        private float _counterAnim;
        private float _badgeAnim;
        private float _segmentFillAnim;
        private float _segmentFillTarget;
        private int _lastReadyCount = -1;
        private int _lastPlayerCount = -1;
        private float _badgeBlinkT;

        private bool _chatResizing;
        private Vector2 _chatResizeMouseStart;
        private Vector2 _chatResizeSizeStart;

        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(AnimatedBackground, LayoutPreset.Wide);
            SetAnchorPreset(FxOverlay, LayoutPreset.Wide);
            SetAnchorPreset(NavFade, LayoutPreset.Wide);
            SetAnchorPreset(RightSideContent, LayoutPreset.Wide);
            SetAnchorPreset(StatusPips, LayoutPreset.TopRight);
            SetGrowHorizontal(StatusPips, GrowDirection.Begin);
            SetMarginRight(StatusPips, -32);
            SetMarginTop(StatusPips, 32);

            RightSide.SetWidth = 320;

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            BuildPixelLogo();
            BuildBrandDash();
            BuildReadySegments();
            StyleChatChrome();
            InitNavItems();
            InitChatResize();

            Chat.MinSize = new Vector2(260, 120);

            ReadyButton.Label.Visible = false;
            CharacterNavButton.Label.Visible = false;
            OptionsButton.Label.Visible = false;
            LeaveButton.Label.Visible = false;

            ReadyButton.OnPressed += _ => SelectNav(NavId.Play);
            CharacterNavButton.OnPressed += _ => SelectNav(NavId.Character);
            OptionsButton.OnPressed += _ =>
            {
                SelectNav(NavId.Settings);
                UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            };
            LeaveButton.OnPressed += _ =>
            {
                SelectNav(NavId.Quit);
                _consoleHost.ExecuteCommand("disconnect");
            };

            WireHover(ReadyButton, NavId.Play);
            WireHover(CharacterNavButton, NavId.Character);
            WireHover(OptionsButton, NavId.Settings);
            WireHover(LeaveButton, NavId.Quit);

            CollapseButton.Visible = false;
            ExpandPanel.Visible = false;

            // Snap visuals once so first frame isn't empty.
            AnimateNav(1f);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ChatMsgCount.Text = Loc.GetString("ui-lobby-expedition-chat-msg-count",
                ("count", Chat.Contents.EntryCount));

            AnimateNav(Math.Clamp(args.DeltaSeconds * NavAnimSpeed, 0f, 1f));
            AnimateReadyCounter(args.DeltaSeconds);
            UpdateChatResizeCursor();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    StatusPips.Visible = true;
                    FxOverlay.Visible = true;
                    ChatShell.Visible = true;
                    if (_selected == NavId.Character)
                        SelectNav(NavId.Play);
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    ChatShell.Visible = false;
                    SelectNav(NavId.Character);

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }

        public void UpdateReadyVisuals(bool isGameStarted, bool areWeReady, int readyCount, int playerCount)
        {
            _gameStarted = isGameStarted;
            _readyTeal = !isGameStarted && areWeReady;

            var total = Math.Max(1, playerCount);
            _segmentFillTarget = readyCount / (float) total * ReadySegments;

            if (readyCount != _lastReadyCount || playerCount != _lastPlayerCount)
            {
                _lastReadyCount = readyCount;
                _lastPlayerCount = playerCount;
                ReadyCountLabel.SetMarkup(Loc.GetString("ui-lobby-expedition-ready-count-markup",
                    ("ready", readyCount),
                    ("total", playerCount)));
            }

            _counterWanted = !isGameStarted;
            _badgeWanted = !isGameStarted && areWeReady;

            // Keep in tree while animating out.
            ReadyCounterBox.Visible = _counterWanted || _counterAnim > 0.01f;

            PlaySubLabel.Text = Loc.GetString(
                !isGameStarted && areWeReady
                    ? "ui-lobby-expedition-play-sub-ready"
                    : isGameStarted
                        ? "ui-lobby-expedition-play-sub-join"
                        : "ui-lobby-expedition-play-sub");
        }

        private void AnimateReadyCounter(float dt)
        {
            var counterT = Math.Clamp(dt * CounterAnimSpeed, 0f, 1f);
            var badgeT = Math.Clamp(dt * BadgeAnimSpeed, 0f, 1f);
            var segT = Math.Clamp(dt * SegmentAnimSpeed, 0f, 1f);

            var counterTarget = _counterWanted ? 1f : 0f;
            _counterAnim = Lerp(_counterAnim, counterTarget, counterT);
            if (MathF.Abs(_counterAnim - counterTarget) < 0.001f)
                _counterAnim = counterTarget;

            var badgeTarget = _badgeWanted ? 1f : 0f;
            _badgeAnim = Lerp(_badgeAnim, badgeTarget, badgeT);
            if (MathF.Abs(_badgeAnim - badgeTarget) < 0.001f)
                _badgeAnim = badgeTarget;

            _segmentFillAnim = Lerp(_segmentFillAnim, _segmentFillTarget, segT);

            // Ease-out for a softer appear (approx).
            var counterEase = 1f - MathF.Pow(1f - _counterAnim, 2f);
            var badgeEase = 1f - MathF.Pow(1f - _badgeAnim, 2f);

            ReadyCounterBox.Visible = _counterWanted || _counterAnim > 0.01f;
            ReadyCounterBox.ModulateSelfOverride = Color.White.WithAlpha(counterEase);
            // Slight slide-down on appear.
            ReadyCounterBox.Margin = new Thickness(0, (1f - counterEase) * -8f, 0, 6);

            ReadyBadgeClip.MaxHeight = BadgeExpandedHeight * badgeEase;
            ReadyBadgeClip.ModulateSelfOverride = Color.White.WithAlpha(badgeEase);
            ReadyBadgeClip.Visible = badgeEase > 0.01f || _badgeWanted;

            // Pixel segments — interpolate fill smoothly.
            var filled = _segmentFillAnim;
            for (var i = 0; i < ReadySegments; i++)
            {
                var segProgress = Math.Clamp(filled - i, 0f, 1f);
                Color color;
                if (segProgress <= 0.01f)
                {
                    color = Color.FromHex("#1A1008");
                }
                else if (_readyTeal && i >= (int) filled - 1 && i < filled)
                {
                    color = Color.InterpolateBetween(ColorGold, ColorTeal, segProgress);
                }
                else
                {
                    color = Color.InterpolateBetween(Color.FromHex("#1A1008"), ColorGold, segProgress);
                }

                _readySegments[i].PanelOverride = new StyleBoxFlat { BackgroundColor = color };
                _readySegments[i].ModulateSelfOverride = Color.White.WithAlpha(0.35f + 0.65f * counterEase);
            }

            // Blinking ready dot (Figma steps blink).
            if (_badgeWanted || _badgeAnim > 0.01f)
            {
                _badgeBlinkT += dt;
                var on = (_badgeBlinkT % 1f) < 0.5f;
                ReadyBadgeDot.ModulateSelfOverride = Color.White.WithAlpha(on ? 1f : 0.15f);
            }
        }

        private void SelectNav(NavId id)
        {
            _selected = id;
        }

        private void WireHover(Button button, NavId id)
        {
            button.OnMouseEntered += _ => _hovered = id;
            button.OnMouseExited += _ =>
            {
                if (_hovered == id)
                    _hovered = null;
            };
        }

        private void InitNavItems()
        {
            _navItems[(int) NavId.Play] = new NavItem(ReadyAccent, ReadyTitle, PlaySubLabel, ReadyHairline);
            _navItems[(int) NavId.Character] = new NavItem(CharacterAccent, CharacterTitle, CharacterSub, CharacterHairline);
            _navItems[(int) NavId.Settings] = new NavItem(SettingsAccent, SettingsTitle, SettingsSub, SettingsHairline);
            _navItems[(int) NavId.Quit] = new NavItem(QuitAccent, QuitTitle, QuitSub, QuitHairline);
        }

        private void AnimateNav(float t)
        {
            for (var i = 0; i < _navItems.Length; i++)
            {
                var id = (NavId) i;
                var item = _navItems[i];
                var selected = _selected == id;
                var hovered = _hovered == id;
                var playReady = id == NavId.Play && _readyTeal;

                float targetW = 3f;
                float targetH = 8f;
                var titleTarget = ColorDim;
                var subTarget = ColorSubDim;
                var accentTarget = ColorAccentIdle;
                var lineTarget = ColorLineIdle;

                if (playReady)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = ColorTeal;
                    subTarget = ColorSubLit;
                    accentTarget = ColorTeal;
                    lineTarget = Color.FromHex("#4AF0D033");
                }
                else if (selected)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = ColorGold;
                    subTarget = ColorSubLit;
                    accentTarget = ColorGold;
                    lineTarget = ColorLineLit;
                }
                else if (hovered)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = ColorHover;
                    subTarget = ColorSubLit;
                    accentTarget = ColorAccentHover;
                    lineTarget = ColorLineLit;
                }

                item.AccentW = Lerp(item.AccentW, targetW, t);
                item.AccentH = Lerp(item.AccentH, targetH, t);
                item.TitleColor = Color.InterpolateBetween(item.TitleColor, titleTarget, t);
                item.SubColor = Color.InterpolateBetween(item.SubColor, subTarget, t);
                item.AccentColor = Color.InterpolateBetween(item.AccentColor, accentTarget, t);
                item.LineColor = Color.InterpolateBetween(item.LineColor, lineTarget, t);

                var w = MathF.Round(item.AccentW);
                var h = MathF.Round(item.AccentH);
                w = Math.Clamp(w, 3f, 8f);
                h = Math.Clamp(h, 8f, 32f);
                // Keep min==max to avoid layout constraint crashes.
                item.Accent.MinSize = new Vector2(w, h);
                item.Accent.MaxSize = new Vector2(w, h);
                item.Accent.PanelOverride = new StyleBoxFlat { BackgroundColor = item.AccentColor };
                item.Title.FontColorOverride = item.TitleColor;
                item.Sub.FontColorOverride = item.SubColor;
                item.Hairline.PanelOverride = new StyleBoxFlat { BackgroundColor = item.LineColor };
            }
        }

        private static float Lerp(float a, float b, float t) => a + (b - a) * t;

        private void InitChatResize()
        {
            ChatResizeGrip.DefaultCursorShape = CursorShape.Crosshair;
            ChatResizeGrip.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick)
                    return;

                _chatResizing = true;
                _chatResizeMouseStart = args.PointerLocation.Position / UIScale;
                _chatResizeSizeStart = new Vector2(ChatShell.Width, ChatShell.Height);
                args.Handle();
            };

            // Global mouse tracking while dragging.
            ChatResizeGrip.OnKeyBindUp += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick)
                    return;
                _chatResizing = false;
            };
        }

        private void UpdateChatResizeCursor()
        {
            if (!_chatResizing)
                return;

            var mouse = UserInterfaceManager.MousePositionScaled.Position;
            var delta = mouse - _chatResizeMouseStart;
            // Grip is top-right: drag right = wider, drag up = taller.
            var newW = Math.Clamp(_chatResizeSizeStart.X + delta.X, ChatShell.MinWidth, ChatShell.MaxWidth);
            var newH = Math.Clamp(_chatResizeSizeStart.Y - delta.Y, ChatShell.MinHeight, ChatShell.MaxHeight);
            ChatShell.SetSize = new Vector2(newW, newH);
        }

        protected override void KeyBindUp(GUIBoundKeyEventArgs args)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                _chatResizing = false;

            base.KeyBindUp(args);
        }

        protected override void MouseMove(GUIMouseMoveEventArgs args)
        {
            base.MouseMove(args);

            if (!_chatResizing)
                return;

            var delta = args.GlobalPosition - _chatResizeMouseStart;
            var newW = Math.Clamp(_chatResizeSizeStart.X + delta.X, ChatShell.MinWidth, ChatShell.MaxWidth);
            var newH = Math.Clamp(_chatResizeSizeStart.Y - delta.Y, ChatShell.MinHeight, ChatShell.MaxHeight);
            ChatShell.SetSize = new Vector2(newW, newH);
        }

        private void StyleChatChrome()
        {
            Chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent
            };
            Chat.ChatWindowPanel.RemoveStyleClass("ChatPanel");
            Chat.ChatWindowPanel.RemoveStyleClass("StyleNano.StyleClassChatPanel");

            Chat.ChatInput.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#02030AE6"),
                BorderColor = Color.FromHex("#F0A83040"),
                BorderThickness = new Thickness(1, 1, 0, 0),
            };
            Chat.ChatInput.RemoveStyleClass(StyleNano.StyleClassChatSubPanel);
        }

        private void BuildPixelLogo()
        {
            var pattern = new[,]
            {
                { 1, 1, 1, 1, 1 },
                { 1, 0, 0, 0, 0 },
                { 1, 1, 1, 1, 0 },
                { 1, 0, 0, 0, 0 },
                { 1, 1, 1, 1, 1 },
            };

            PixelLogo.RemoveAllChildren();
            PixelLogo.Orientation = LayoutOrientation.Horizontal;
            PixelLogo.SeparationOverride = 3;

            for (var col = 0; col < 5; col++)
            {
                var column = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    SeparationOverride = 3
                };

                for (var row = 0; row < 5; row++)
                {
                    var on = pattern[row, col] == 1;
                    column.AddChild(new PanelContainer
                    {
                        MinSize = new Vector2(6, 6),
                        MaxSize = new Vector2(6, 6),
                        PanelOverride = new StyleBoxFlat
                        {
                            BackgroundColor = on ? ColorGold : Color.Transparent
                        }
                    });
                }

                PixelLogo.AddChild(column);
            }
        }

        private void BuildBrandDash()
        {
            BrandDash.RemoveAllChildren();
            BrandDash.Orientation = LayoutOrientation.Horizontal;
            BrandDash.SeparationOverride = 2;

            for (var i = 0; i < BrandDashSegments; i++)
            {
                var wide = i % 3 == 0;
                var alpha = Math.Clamp(1f - i * 0.03f, 0.15f, 1f);
                var baseColor = wide ? ColorGold : Color.FromHex("#2A1A08");
                BrandDash.AddChild(new PanelContainer
                {
                    MinSize = new Vector2(wide ? 6 : 3, 2),
                    MaxSize = new Vector2(wide ? 6 : 3, 2),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = baseColor.WithAlpha(alpha)
                    }
                });
            }
        }

        private void BuildReadySegments()
        {
            ReadySegmentRow.RemoveAllChildren();
            ReadySegmentRow.Orientation = LayoutOrientation.Horizontal;
            ReadySegmentRow.SeparationOverride = 2;

            for (var i = 0; i < ReadySegments; i++)
            {
                var seg = new PanelContainer
                {
                    MinSize = new Vector2(4, 8),
                    MaxSize = new Vector2(4, 8),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1A1008") }
                };
                _readySegments[i] = seg;
                ReadySegmentRow.AddChild(seg);
            }
        }

        private enum NavId : byte
        {
            Play = 0,
            Character = 1,
            Settings = 2,
            Quit = 3
        }

        private sealed class NavItem
        {
            public readonly PanelContainer Accent;
            public readonly Label Title;
            public readonly Label Sub;
            public readonly PanelContainer Hairline;

            public float AccentW = 3f;
            public float AccentH = 8f;
            public Color TitleColor = ColorDim;
            public Color SubColor = ColorSubDim;
            public Color AccentColor = ColorAccentIdle;
            public Color LineColor = ColorLineIdle;

            public NavItem(PanelContainer accent, Label title, Label sub, PanelContainer hairline)
            {
                Accent = accent;
                Title = title;
                Sub = sub;
                Hairline = hairline;
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup
        }
    }
}
