using System.Numerics;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        private const int ReadySegments = 16;
        private const int BrandDashSegments = 24;
        private const float NavAnimSpeed = 12f;
        private const float CounterAnimSpeed = 8f;
        private const float BadgeAnimSpeed = 10f;
        private const float SegmentAnimSpeed = 6f;
        private const float PaletteAnimSpeed = 1.2f; // ~0.9s feel
        private const float BadgeExpandedHeight = 28f;

        private const float LobbyClickGain = 0.25f;
        private const float LobbyReleaseGain = 0.20f;
        private const float LobbyHoverGain = 0.22f;

        private static readonly ResPath LobbyClickPath = new("/Audio/_CitadelStation/Menu/buttonclick.ogg");
        private static readonly ResPath LobbyReleasePath = new("/Audio/_CitadelStation/Menu/buttonclickrelease.ogg");
        private static readonly ResPath LobbyHoverPath = new("/Audio/_CitadelStation/Menu/buttonrollover.ogg");

        private static readonly Color ColorTeal = Color.FromHex("#4AF0D0");

        // Animated palette (lerps toward server or black-hole targets).
        // Animated palette (lerps toward server or black-hole targets).
        private Color _p = Color.FromHex("#E03030");
        private Color _pBright = Color.FromHex("#FF5555");
        private Color _pDim = Color.FromHex("#8B1010");
        private Color _pMut = Color.FromHex("#8B3030");
        private Color _pFont = Color.FromHex("#C02020"); // Figma PFNT — saturated dash accents
        private Color _labelDim = Color.FromHex("#8B3838");
        private Color _labelHov = Color.FromHex("#FFAAAA");
        private Color _subDim = Color.FromHex("#1A0808");
        private Color _subLit = Color.FromHex("#5A2020");
        private Color _accentIdle = Color.FromHex("#200808");
        private Color _accentHover = Color.FromHex("#FF8888");
        private Color _lineIdle = Color.FromHex("#20080880");
        private Color _lineLit = Color.FromHex("#E0303033");
        private Color _dashIdle = Color.FromHex("#200808");
        private Color _segEmpty = Color.FromHex("#3A1010");

        private LobbyBgMode _bgMode = LobbyBgMode.Server;
        private readonly List<PanelContainer> _logoCells = new();
        private readonly List<PanelContainer> _dashCells = new();

        private readonly PanelContainer[] _readySegments = new PanelContainer[ReadySegments];
        private readonly NavItem[] _navItems = new NavItem[4];

        private NavId? _selected;
        private NavId? _hovered;
        private bool _readyTeal;
        private bool _gameStarted;

        private bool _counterWanted = true;
        private bool _badgeWanted;
        private float _counterAnim;
        private float _badgeAnim;
        private float _segmentFillAnim;
        private float _segmentFillTarget;
        private int _lastReadyCount = -1;
        private int _lastPlayerCount = -1;
        private float _badgeBlinkT;

        private bool _chatResizing;
        private Vector2 _chatResizeMouseStart;
        private Vector2 _chatResizeSizeStart;

        private IAudioSource? _lobbyClickSource;
        private IAudioSource? _lobbyReleaseSource;
        private IAudioSource? _lobbyHoverSource;
        private readonly List<Button> _lobbySoundButtons = new();
        private readonly Dictionary<Button, bool> _lobbyButtonWasHovered = new();

        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IAudioManager _audioManager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(AnimatedBackground, LayoutPreset.Wide);
            SetAnchorPreset(FxOverlay, LayoutPreset.Wide);
            SetAnchorPreset(NavFade, LayoutPreset.Wide);
            SetAnchorPreset(RightSideContent, LayoutPreset.Wide);
            SetAnchorPreset(StatusPips, LayoutPreset.TopRight);

            // Backdrop must stay under chrome — never paint over the menu.
            AnimatedBackground.SetPositionFirst();
            FxOverlay.SetPositionLast();
            MainContainer.SetPositionLast();
            StatusPips.SetPositionLast();
            SetGrowHorizontal(StatusPips, GrowDirection.Begin);
            SetMarginRight(StatusPips, -32);
            SetMarginTop(StatusPips, 32);

            RightSide.SetWidth = 320;

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            BuildPixelLogo();
            BuildBrandDash();
            BuildReadySegments();
            StyleChatChrome();
            InitNavItems();
            InitChatResize();
            InitLobbyButtonSounds();
            ApplyPaletteChrome(snap: true);

            Chat.MinSize = new Vector2(260, 120);

            ReadyButton.Label.Visible = false;
            CharacterNavButton.Label.Visible = false;
            OptionsButton.Label.Visible = false;
            LeaveButton.Label.Visible = false;
            ReadyButton.OnPressed += _ => SelectNav(NavId.Play);
            CharacterNavButton.OnPressed += _ => SelectNav(NavId.Character);
            OptionsButton.OnPressed += _ =>
            {
                SelectNav(NavId.Settings);
                UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            };
            LeaveButton.OnPressed += _ =>
            {
                SelectNav(NavId.Quit);
                _consoleHost.ExecuteCommand("disconnect");
            };

            BgPrevButton.OnPressed += _ => AnimatedBackground.SwitchBackground();
            BgNextButton.OnPressed += _ => AnimatedBackground.SwitchBackground();
            AnimatedBackground.ModeChanged += OnBackgroundModeChanged;
            OnBackgroundModeChanged(AnimatedBackground.CurrentMode);

            WireHover(ReadyButton, NavId.Play);
            WireHover(CharacterNavButton, NavId.Character);
            WireHover(OptionsButton, NavId.Settings);
            WireHover(LeaveButton, NavId.Quit);

            CollapseButton.Visible = false;
            ExpandPanel.Visible = false;

            AnimateNav(1f);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ChatMsgCount.Text = Loc.GetString("ui-lobby-expedition-chat-msg-count",
                ("count", Chat.Contents.EntryCount));

            var dt = args.DeltaSeconds;
            AnimatePalette(Math.Clamp(dt * PaletteAnimSpeed, 0f, 1f));
            AnimateNav(Math.Clamp(dt * NavAnimSpeed, 0f, 1f));
            AnimateReadyCounter(dt);
            UpdateLobbyButtonHoverSounds();
            UpdateChatResizeCursor();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    StatusPips.Visible = true;
                    FxOverlay.Visible = true;
                    ChatShell.Visible = true;
                    if (_selected == NavId.Character)
                        SelectNav(NavId.Play);
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    ChatShell.Visible = false;
                    SelectNav(NavId.Character);

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }

        public void UpdateReadyVisuals(bool isGameStarted, bool areWeReady, int readyCount, int playerCount)
        {
            _gameStarted = isGameStarted;
            _readyTeal = !isGameStarted && areWeReady;

            var total = Math.Max(1, playerCount);
            _segmentFillTarget = readyCount / (float) total * ReadySegments;

            if (readyCount != _lastReadyCount || playerCount != _lastPlayerCount)
            {
                _lastReadyCount = readyCount;
                _lastPlayerCount = playerCount;
                RefreshReadyCountMarkup();
            }

            _counterWanted = !isGameStarted;
            _badgeWanted = !isGameStarted && areWeReady;
            ReadyCounterBox.Visible = _counterWanted || _counterAnim > 0.01f;

            PlaySubLabel.Text = Loc.GetString(
                !isGameStarted && areWeReady
                    ? "ui-lobby-expedition-play-sub-ready"
                    : isGameStarted
                        ? "ui-lobby-expedition-play-sub-join"
                        : "ui-lobby-expedition-play-sub");
        }

        private void OnBackgroundModeChanged(LobbyBgMode mode)
        {
            _bgMode = mode;
            BgViewLabel.Text = Loc.GetString(mode == LobbyBgMode.BlackHole
                ? "ui-lobby-expedition-bg-blackhole"
                : "ui-lobby-expedition-bg-server");
            RefreshReadyCountMarkup();
        }

        private void RefreshReadyCountMarkup()
        {
            if (_lastReadyCount < 0)
                return;

            var key = _bgMode == LobbyBgMode.BlackHole
                ? "ui-lobby-expedition-ready-count-markup-blackhole"
                : "ui-lobby-expedition-ready-count-markup-server";
            ReadyCountLabel.SetMarkup(Loc.GetString(key,
                ("ready", _lastReadyCount),
                ("total", Math.Max(0, _lastPlayerCount))));
        }

        private void AnimatePalette(float t)
        {
            GetPaletteTargets(_bgMode,
                out var p, out var pBright, out var pDim, out var pMut, out var pFont,
                out var labelDim, out var labelHov, out var subDim, out var subLit,
                out var accentIdle, out var accentHover, out var lineIdle, out var lineLit,
                out var dashIdle, out var segEmpty);

            _p = Color.InterpolateBetween(_p, p, t);
            _pBright = Color.InterpolateBetween(_pBright, pBright, t);
            _pDim = Color.InterpolateBetween(_pDim, pDim, t);
            _pMut = Color.InterpolateBetween(_pMut, pMut, t);
            _pFont = Color.InterpolateBetween(_pFont, pFont, t);
            _labelDim = Color.InterpolateBetween(_labelDim, labelDim, t);
            _labelHov = Color.InterpolateBetween(_labelHov, labelHov, t);
            _subDim = Color.InterpolateBetween(_subDim, subDim, t);
            _subLit = Color.InterpolateBetween(_subLit, subLit, t);
            _accentIdle = Color.InterpolateBetween(_accentIdle, accentIdle, t);
            _accentHover = Color.InterpolateBetween(_accentHover, accentHover, t);
            _lineIdle = Color.InterpolateBetween(_lineIdle, lineIdle, t);
            _lineLit = Color.InterpolateBetween(_lineLit, lineLit, t);
            _dashIdle = Color.InterpolateBetween(_dashIdle, dashIdle, t);
            _segEmpty = Color.InterpolateBetween(_segEmpty, segEmpty, t);

            ApplyPaletteChrome(snap: false);
        }

        private static void GetPaletteTargets(
            LobbyBgMode mode,
            out Color p, out Color pBright, out Color pDim, out Color pMut, out Color pFont,
            out Color labelDim, out Color labelHov, out Color subDim, out Color subLit,
            out Color accentIdle, out Color accentHover, out Color lineIdle, out Color lineLit,
            out Color dashIdle, out Color segEmpty)
        {
            if (mode == LobbyBgMode.BlackHole)
            {
                p = Color.FromHex("#C89020");
                pBright = Color.FromHex("#F0C040");
                pDim = Color.FromHex("#7A5010");
                pMut = Color.FromHex("#5A3C10");
                pFont = Color.FromHex("#A07018");
                labelDim = Color.FromHex("#4A3010");
                labelHov = Color.FromHex("#F8D870");
                subDim = Color.FromHex("#251800");
                subLit = Color.FromHex("#5A3C10");
                accentIdle = Color.FromHex("#221500");
                accentHover = Color.FromHex("#FFCC60");
                lineIdle = Color.FromHex("#22150080");
                lineLit = Color.FromHex("#C8902033");
                dashIdle = Color.FromHex("#221500");
                segEmpty = Color.FromHex("#2A1A08");
            }
            else
            {
                p = Color.FromHex("#E03030");
                pBright = Color.FromHex("#FF5555");
                pDim = Color.FromHex("#8B1010");
                pMut = Color.FromHex("#8B3030");
                pFont = Color.FromHex("#C02020");
                labelDim = Color.FromHex("#8B3838");
                labelHov = Color.FromHex("#FFAAAA");
                subDim = Color.FromHex("#1A0808");
                subLit = Color.FromHex("#5A2020");
                accentIdle = Color.FromHex("#200808");
                accentHover = Color.FromHex("#FF8888");
                lineIdle = Color.FromHex("#20080880");
                lineLit = Color.FromHex("#E0303033");
                dashIdle = Color.FromHex("#200808");
                segEmpty = Color.FromHex("#3A1010");
            }
        }

        private void ApplyPaletteChrome(bool snap)
        {
            BrandTitle.FontColorOverride = _p;
            BrandSubtitle.FontColorOverride = _pMut;
            NavHeaderLabel.FontColorOverride = _pMut;
            BgViewHeader.FontColorOverride = _pMut;
            BgViewLabel.FontColorOverride = _p;
            FooterLabel.FontColorOverride = _subDim;
            ChatHeaderLabel.FontColorOverride = _p;
            ChatMsgCount.FontColorOverride = _pMut;
            ChatHeaderDot.PanelOverride = new StyleBoxFlat { BackgroundColor = _p };
            ChatResizeGrip.PanelOverride = new StyleBoxFlat { BackgroundColor = _p.WithAlpha(0.35f) };

            ChatOuterPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#050202FF"),
                BorderColor = _p.WithAlpha(0.35f),
                BorderThickness = new Thickness(1),
            };

            Chat.ChatInput.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#050202FF"),
                BorderColor = _p.WithAlpha(0.30f),
                BorderThickness = new Thickness(1, 1, 0, 0),
            };

            NavFade.EdgeColor = _p;
            NavFade.BaseColor = Color.FromHex("#030101");

            PipNetDot.PanelOverride = new StyleBoxFlat { BackgroundColor = _p };
            PipNetLabel.FontColorOverride = _p;
            PipSrvDot.PanelOverride = new StyleBoxFlat { BackgroundColor = _pDim };
            PipSrvLabel.FontColorOverride = _pDim;
            PipVceDot.PanelOverride = new StyleBoxFlat { BackgroundColor = _segEmpty };
            PipVceLabel.FontColorOverride = _pMut;

            // Theme switcher arrows — FontColorOverride (Modulate alone stays white from stylesheet)
            BgPrevButton.ModulateSelfOverride = Color.White;
            BgNextButton.ModulateSelfOverride = Color.White;
            BgPrevButton.Label.FontColorOverride = _p;
            BgNextButton.Label.FontColorOverride = _p;
            BgPrevButton.Label.Visible = true;
            BgNextButton.Label.Visible = true;

            foreach (var cell in _logoCells)
            {
                if (cell.PanelOverride is StyleBoxFlat { BackgroundColor.A: > 0 })
                    cell.PanelOverride = new StyleBoxFlat { BackgroundColor = _pBright };
            }

            for (var i = 0; i < _dashCells.Count; i++)
            {
                var wide = i % 3 == 0;
                // Figma: wide = PFNT solid; narrow = dark idle, mild fade only
                var alpha = wide
                    ? Math.Clamp(1f - i * 0.015f, 0.88f, 1f)
                    : Math.Clamp(1f - i * 0.025f, 0.55f, 1f);
                var c = wide ? _pFont : _dashIdle;
                _dashCells[i].PanelOverride = new StyleBoxFlat { BackgroundColor = c.WithAlpha(alpha) };
            }

            if (snap)
                NavFade.InvalidateMeasure();
        }

        private void AnimateReadyCounter(float dt)
        {
            var counterT = Math.Clamp(dt * CounterAnimSpeed, 0f, 1f);
            var badgeT = Math.Clamp(dt * BadgeAnimSpeed, 0f, 1f);
            var segT = Math.Clamp(dt * SegmentAnimSpeed, 0f, 1f);

            var counterTarget = _counterWanted ? 1f : 0f;
            _counterAnim = Lerp(_counterAnim, counterTarget, counterT);
            if (MathF.Abs(_counterAnim - counterTarget) < 0.001f)
                _counterAnim = counterTarget;

            var badgeTarget = _badgeWanted ? 1f : 0f;
            _badgeAnim = Lerp(_badgeAnim, badgeTarget, badgeT);
            if (MathF.Abs(_badgeAnim - badgeTarget) < 0.001f)
                _badgeAnim = badgeTarget;

            _segmentFillAnim = Lerp(_segmentFillAnim, _segmentFillTarget, segT);

            var counterEase = 1f - MathF.Pow(1f - _counterAnim, 2f);
            var badgeEase = 1f - MathF.Pow(1f - _badgeAnim, 2f);

            ReadyCounterBox.Visible = _counterWanted || _counterAnim > 0.01f;
            ReadyCounterBox.ModulateSelfOverride = Color.White.WithAlpha(counterEase);
            ReadyCounterBox.Margin = new Thickness(0, (1f - counterEase) * -8f, 0, 6);

            ReadyBadgeClip.MaxHeight = BadgeExpandedHeight * badgeEase;
            ReadyBadgeClip.ModulateSelfOverride = Color.White.WithAlpha(badgeEase);
            ReadyBadgeClip.Visible = badgeEase > 0.01f || _badgeWanted;

            var filled = _segmentFillAnim;
            for (var i = 0; i < ReadySegments; i++)
            {
                var segProgress = Math.Clamp(filled - i, 0f, 1f);
                Color color;
                if (segProgress <= 0.01f)
                    color = _segEmpty;
                else if (_readyTeal && i >= (int) filled - 1 && i < filled)
                    color = Color.InterpolateBetween(_p, ColorTeal, segProgress);
                else
                    color = Color.InterpolateBetween(_segEmpty, _p, segProgress);

                _readySegments[i].PanelOverride = new StyleBoxFlat { BackgroundColor = color };
                _readySegments[i].ModulateSelfOverride = Color.White.WithAlpha(0.35f + 0.65f * counterEase);
            }

            if (_badgeWanted || _badgeAnim > 0.01f)
            {
                _badgeBlinkT += dt;
                var on = (_badgeBlinkT % 1f) < 0.5f;
                ReadyBadgeDot.ModulateSelfOverride = Color.White.WithAlpha(on ? 1f : 0.15f);
            }
        }

        private void SelectNav(NavId id) => _selected = id;

        private void InitLobbyButtonSounds()
        {
            var volume = _cfg.GetCVar(CCVars.InterfaceVolume);
            _lobbyClickSource = CreateLobbyUiSource(LobbyClickPath, LobbyClickGain * volume);
            _lobbyReleaseSource = CreateLobbyUiSource(LobbyReleasePath, LobbyReleaseGain * volume);
            _lobbyHoverSource = CreateLobbyUiSource(LobbyHoverPath, LobbyHoverGain * volume);

            WireLobbyButtonSound(ReadyButton);
            WireLobbyButtonSound(CharacterNavButton);
            WireLobbyButtonSound(OptionsButton);
            WireLobbyButtonSound(LeaveButton);
            WireLobbyButtonSound(BgPrevButton);
            WireLobbyButtonSound(BgNextButton);
        }

        private IAudioSource? CreateLobbyUiSource(ResPath path, float gain)
        {
            if (!_resourceCache.TryGetResource(path, out AudioResource? resource))
                return null;

            var source = _audioManager.CreateAudioSource(resource);
            if (source == null)
                return null;

            source.Global = true;
            source.Gain = gain;
            return source;
        }

        private void WireLobbyButtonSound(Button button)
        {
            // Content must Ignore hits so the Button itself receives hover enter/exit.
            IgnoreMouseOnDescendants(button);

            // Mute default global UI click/hover — only Citadel lobby sounds here.
            button.MuteSounds = true;
            button.OnButtonDown += _ => _lobbyClickSource?.Restart();
            button.OnButtonUp += _ => _lobbyReleaseSource?.Restart();

            _lobbySoundButtons.Add(button);
            _lobbyButtonWasHovered[button] = false;
        }

        private static void IgnoreMouseOnDescendants(Control root)
        {
            foreach (var child in root.Children)
            {
                child.MouseFilter = MouseFilterMode.Ignore;
                IgnoreMouseOnDescendants(child);
            }
        }

        /// <summary>
        /// Plays hover when a lobby button becomes hovered. Uses IsHovered polling because
        /// nested content can steal OnMouseEntered even when click still reaches the button.
        /// </summary>
        private void UpdateLobbyButtonHoverSounds()
        {
            foreach (var button in _lobbySoundButtons)
            {
                var hovered = button.IsHovered;
                if (hovered && !_lobbyButtonWasHovered[button])
                    _lobbyHoverSource?.Restart();

                _lobbyButtonWasHovered[button] = hovered;
            }
        }

        private void WireHover(Button button, NavId id)
        {
            button.OnMouseEntered += _ => _hovered = id;
            button.OnMouseExited += _ =>
            {
                if (_hovered == id)
                    _hovered = null;
            };
        }

        private void InitNavItems()
        {
            _navItems[(int) NavId.Play] = new NavItem(ReadyAccent, ReadyTitle, PlaySubLabel, ReadyHairline);
            _navItems[(int) NavId.Character] = new NavItem(CharacterAccent, CharacterTitle, CharacterSub, CharacterHairline);
            _navItems[(int) NavId.Settings] = new NavItem(SettingsAccent, SettingsTitle, SettingsSub, SettingsHairline);
            _navItems[(int) NavId.Quit] = new NavItem(QuitAccent, QuitTitle, QuitSub, QuitHairline);
        }

        private void AnimateNav(float t)
        {
            for (var i = 0; i < _navItems.Length; i++)
            {
                var id = (NavId) i;
                var item = _navItems[i];
                var selected = _selected == id;
                var hovered = _hovered == id;
                var playReady = id == NavId.Play && _readyTeal;

                float targetW = 3f;
                float targetH = 8f;
                var titleTarget = _labelDim;
                var subTarget = _subDim;
                var accentTarget = _accentIdle;
                var lineTarget = _lineIdle;

                if (playReady)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = ColorTeal;
                    subTarget = _subLit;
                    accentTarget = ColorTeal;
                    lineTarget = Color.FromHex("#4AF0D033");
                }
                else if (selected)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = _p;
                    subTarget = _subLit;
                    accentTarget = _p;
                    lineTarget = _lineLit;
                }
                else if (hovered)
                {
                    targetW = 8f;
                    targetH = 32f;
                    titleTarget = _labelHov;
                    subTarget = _subLit;
                    accentTarget = _accentHover;
                    lineTarget = _lineLit;
                }

                item.AccentW = Lerp(item.AccentW, targetW, t);
                item.AccentH = Lerp(item.AccentH, targetH, t);
                item.TitleColor = Color.InterpolateBetween(item.TitleColor, titleTarget, t);
                item.SubColor = Color.InterpolateBetween(item.SubColor, subTarget, t);
                item.AccentColor = Color.InterpolateBetween(item.AccentColor, accentTarget, t);
                item.LineColor = Color.InterpolateBetween(item.LineColor, lineTarget, t);

                var w = Math.Clamp(MathF.Round(item.AccentW), 3f, 8f);
                var h = Math.Clamp(MathF.Round(item.AccentH), 8f, 32f);
                item.Accent.MinSize = new Vector2(w, h);
                item.Accent.MaxSize = new Vector2(w, h);
                item.Accent.PanelOverride = new StyleBoxFlat { BackgroundColor = item.AccentColor };
                item.Title.FontColorOverride = item.TitleColor;
                item.Sub.FontColorOverride = item.SubColor;
                item.Hairline.PanelOverride = new StyleBoxFlat { BackgroundColor = item.LineColor };
            }
        }

        private static float Lerp(float a, float b, float t) => a + (b - a) * t;

        private void InitChatResize()
        {
            ChatResizeGrip.DefaultCursorShape = CursorShape.Crosshair;
            ChatResizeGrip.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick)
                    return;

                _chatResizing = true;
                _chatResizeMouseStart = args.PointerLocation.Position / UIScale;
                _chatResizeSizeStart = new Vector2(ChatShell.Width, ChatShell.Height);
                args.Handle();
            };

            ChatResizeGrip.OnKeyBindUp += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick)
                    return;
                _chatResizing = false;
            };
        }

        private void UpdateChatResizeCursor()
        {
            if (!_chatResizing)
                return;

            var mouse = UserInterfaceManager.MousePositionScaled.Position;
            var delta = mouse - _chatResizeMouseStart;
            var newW = Math.Clamp(_chatResizeSizeStart.X + delta.X, ChatShell.MinWidth, ChatShell.MaxWidth);
            var newH = Math.Clamp(_chatResizeSizeStart.Y - delta.Y, ChatShell.MinHeight, ChatShell.MaxHeight);
            ChatShell.SetSize = new Vector2(newW, newH);
        }

        protected override void KeyBindUp(GUIBoundKeyEventArgs args)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                _chatResizing = false;

            base.KeyBindUp(args);
        }

        protected override void MouseMove(GUIMouseMoveEventArgs args)
        {
            base.MouseMove(args);

            if (!_chatResizing)
                return;

            var delta = args.GlobalPosition - _chatResizeMouseStart;
            var newW = Math.Clamp(_chatResizeSizeStart.X + delta.X, ChatShell.MinWidth, ChatShell.MaxWidth);
            var newH = Math.Clamp(_chatResizeSizeStart.Y - delta.Y, ChatShell.MinHeight, ChatShell.MaxHeight);
            ChatShell.SetSize = new Vector2(newW, newH);
        }

        private void StyleChatChrome()
        {
            Chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent
            };
            Chat.ChatWindowPanel.RemoveStyleClass("ChatPanel");
            Chat.ChatWindowPanel.RemoveStyleClass("StyleNano.StyleClassChatPanel");
            Chat.ChatInput.RemoveStyleClass(StyleNano.StyleClassChatSubPanel);
        }

        private void BuildPixelLogo()
        {
            // SS14 pixel glyphs from Figma Make v2 (5 rows × 3 cols each).
            // Cells bumped 5→7 to match perceived size vs EXPEDITION title.
            const float cell = 7f;
            int[][][] glyphs =
            [
                [[1, 1, 1], [1, 0, 0], [1, 1, 1], [0, 0, 1], [1, 1, 1]], // S
                [[1, 1, 1], [1, 0, 0], [1, 1, 1], [0, 0, 1], [1, 1, 1]], // S
                [[0, 1, 0], [1, 1, 0], [0, 1, 0], [0, 1, 0], [1, 1, 1]], // 1
                [[1, 0, 1], [1, 0, 1], [1, 1, 1], [0, 0, 1], [0, 0, 1]], // 4
            ];

            PixelLogo.RemoveAllChildren();
            _logoCells.Clear();
            PixelLogo.Orientation = LayoutOrientation.Horizontal;
            PixelLogo.SeparationOverride = 8;

            foreach (var glyph in glyphs)
            {
                var gBox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    SeparationOverride = 3
                };

                foreach (var row in glyph)
                {
                    var rowBox = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        SeparationOverride = 3
                    };

                    foreach (var c in row)
                    {
                        var panel = new PanelContainer
                        {
                            MinSize = new Vector2(cell, cell),
                            MaxSize = new Vector2(cell, cell),
                            PanelOverride = new StyleBoxFlat
                            {
                                BackgroundColor = c == 1 ? _pBright : Color.Transparent
                            }
                        };
                        if (c == 1)
                            _logoCells.Add(panel);
                        rowBox.AddChild(panel);
                    }

                    gBox.AddChild(rowBox);
                }

                PixelLogo.AddChild(gBox);
            }
        }

        private void BuildBrandDash()
        {
            BrandDash.RemoveAllChildren();
            _dashCells.Clear();
            BrandDash.Orientation = LayoutOrientation.Horizontal;
            BrandDash.SeparationOverride = 2;

            for (var i = 0; i < BrandDashSegments; i++)
            {
                var wide = i % 3 == 0;
                var alpha = wide
                    ? Math.Clamp(1f - i * 0.015f, 0.88f, 1f)
                    : Math.Clamp(1f - i * 0.025f, 0.55f, 1f);
                var panel = new PanelContainer
                {
                    MinSize = new Vector2(wide ? 8 : 4, 3),
                    MaxSize = new Vector2(wide ? 8 : 4, 3),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = (wide ? _pFont : _dashIdle).WithAlpha(alpha)
                    }
                };
                _dashCells.Add(panel);
                BrandDash.AddChild(panel);
            }
        }

        private void BuildReadySegments()
        {
            ReadySegmentRow.RemoveAllChildren();
            ReadySegmentRow.Orientation = LayoutOrientation.Horizontal;
            ReadySegmentRow.SeparationOverride = 2;

            for (var i = 0; i < ReadySegments; i++)
            {
                var seg = new PanelContainer
                {
                    MinSize = new Vector2(4, 8),
                    MaxSize = new Vector2(4, 8),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = _segEmpty }
                };
                _readySegments[i] = seg;
                ReadySegmentRow.AddChild(seg);
            }
        }

        private enum NavId : byte
        {
            Play = 0,
            Character = 1,
            Settings = 2,
            Quit = 3
        }

        private sealed class NavItem
        {
            public readonly PanelContainer Accent;
            public readonly Label Title;
            public readonly Label Sub;
            public readonly PanelContainer Hairline;

            public float AccentW = 3f;
            public float AccentH = 8f;
            public Color TitleColor = Color.FromHex("#8B3838");
            public Color SubColor = Color.FromHex("#1A0808");
            public Color AccentColor = Color.FromHex("#200808");
            public Color LineColor = Color.FromHex("#20080880");

            public NavItem(PanelContainer accent, Label title, Label sub, PanelContainer hairline)
            {
                Accent = accent;
                Title = title;
                Sub = sub;
                Hairline = hairline;
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup
        }
    }
}
