using System.Numerics;
using Content.Shared._CitadelStation.Signboard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._CitadelStation.Signboard.UI;

[GenerateTypedNameReferences]
public sealed partial class SignboardWindow : DefaultWindow
{
    private const string NoStyleId = "";
    private const int MinBrushSize = 1;
    private const int MaxBrushSize = 60;
    private const float DelayCommitSeconds = 0.2f;

    private static readonly Color[] Palette =
    [
        Color.Black, Color.White, Color.Red, Color.Orange,
        Color.Yellow, Color.Lime, Color.Cyan, Color.Blue,
        Color.Magenta, Color.Pink, Color.Gray, new Color(0f, 1f, 0.6f),
        new Color(1f, 0.4f, 0f), new Color(0.2f, 0.6f, 1f), Color.Transparent, new Color(1f, 1f, 0.4f)
    ];

    private readonly List<string> _styleIds = [];
    private bool _dirty;
    private bool _canEdit = true;
    private bool _pixelsLoaded;
    private bool _updatingUi;
    private int _fontScale = 1;
    private int _loadedSize = -1;
    private int _loadedGridW = -1;
    private int _loadedGridH = -1;
    private int _loadedFrameCount = -1;
    private float? _pendingDelay;
    private float _delayCommitTimer;

    public event Action<List<SignboardFrameData>, int>? OnFramesChanged;
    public event Action<int>? OnSizeChanged;
    public event Action<float>? OnDelayChanged;
    public event Action<bool>? OnNeonChanged;
    public event Action<bool>? OnPlayingChanged;
    public event Action<bool>? OnPoweredChanged;
    public event Action<string?>? OnStyleSelected;

    public SignboardWindow()
    {
        RobustXamlLoader.Load(this);

        BrushButton.OnPressed += _ => SetTool(SignboardTool.Brush);
        EraserButton.OnPressed += _ => SetTool(SignboardTool.Eraser);
        FillButton.OnPressed += _ => SetTool(SignboardTool.Fill);
        EyedropperButton.OnPressed += _ => SetTool(SignboardTool.Eyedropper);

        ZoomSlider.OnValueChanged += args =>
        {
            DrawArea.SetZoom(args.Value);
            ZoomValueLabel.Text = $"{(int)MathF.Round(args.Value * 100)}%";
        };
        DrawArea.SetZoom(ZoomSlider.Value);
        ZoomValueLabel.Text = $"{(int)MathF.Round(ZoomSlider.Value * 100)}%";

        BrushSizeSlider.OnValueChanged += args =>
        {
            if (_updatingUi)
                return;
            SetBrushSize((int)MathF.Round(args.Value), syncSlider: false);
        };
        BrushSizeEdit.OnTextEntered += _ => ApplyBrushSizeFromEdit();
        BrushSizeEdit.OnFocusExit += _ => ApplyBrushSizeFromEdit();
        SetBrushSize(1);

        Res64Button.OnPressed += _ => RequestSize(64);
        Res128Button.OnPressed += _ => RequestSize(128);
        Res256Button.OnPressed += _ => RequestSize(256);

        ColorPicker.OnColorChanged += color => DrawArea.BrushColor = color;
        DrawArea.ColorPicked += color =>
        {
            ColorPicker.Color = color;
            DrawArea.BrushColor = color;
        };
        DrawArea.PixelsModified += () => _dirty = true;
        DrawArea.TextPlaced += () =>
        {
            _dirty = true;
            // Stay in text-place mode so the player can stamp repeatedly.
            SyncPendingText();
        };

        foreach (var color in Palette)
        {
            var swatch = new Button
            {
                MinSize = new Vector2(24, 24),
                MaxSize = new Vector2(24, 24),
                ModulateSelfOverride = color.A < 0.01f ? Color.White : color
            };
            var captured = color;
            swatch.OnPressed += _ =>
            {
                ColorPicker.Color = captured;
                DrawArea.BrushColor = captured;
            };
            PaletteGrid.AddChild(swatch);
        }

        FrameOption.OnItemSelected += args =>
        {
            FrameOption.SelectId(args.Id);
            DrawArea.SetActiveFrame(args.Id);
            DrawArea.OnionSkin = OnionCheck.Pressed;
        };

        AddFrameButton.OnPressed += _ =>
        {
            if (!DrawArea.TryAddFrame(Loc.GetString("signboard-frame-default-name", ("n", DrawArea.FrameCount + 1)), copyPrevious: false))
                return;
            _dirty = true;
            RebuildFrameOption();
        };

        RemoveFrameButton.OnPressed += _ =>
        {
            if (!DrawArea.TryRemoveActiveFrame())
                return;
            _dirty = true;
            RebuildFrameOption();
        };

        CopyPrevButton.OnPressed += _ =>
        {
            DrawArea.CopyFromPrevious();
            _dirty = true;
        };

        OnionCheck.OnToggled += args =>
        {
            DrawArea.OnionSkin = args.Pressed;
        };

        DelaySlider.OnValueChanged += args =>
        {
            if (_updatingUi)
                return;
            DelayValueLabel.Text = $"{args.Value:0.00}s";
            // Debounce network commits so dragging stays smooth.
            _pendingDelay = args.Value;
            _delayCommitTimer = DelayCommitSeconds;
        };

        NeonCheck.OnToggled += args =>
        {
            if (!_updatingUi)
                OnNeonChanged?.Invoke(args.Pressed);
        };
        PlayingCheck.OnToggled += args =>
        {
            if (!_updatingUi)
                OnPlayingChanged?.Invoke(args.Pressed);
        };
        PoweredCheck.OnToggled += args =>
        {
            if (!_updatingUi)
                OnPoweredChanged?.Invoke(args.Pressed);
        };

        StyleOption.OnItemSelected += args => StyleOption.SelectId(args.Id);
        ApplyStyleButton.OnPressed += _ =>
        {
            FlushFrames();
            if (StyleOption.SelectedId < 0 || StyleOption.SelectedId >= _styleIds.Count)
                return;
            var id = _styleIds[StyleOption.SelectedId];
            OnStyleSelected?.Invoke(string.IsNullOrEmpty(id) ? null : id);
        };

        FontOption.AddItem(Loc.GetString("signboard-font-pixel"), 0);
        FontOption.AddItem(Loc.GetString("signboard-font-mono"), 1);
        FontOption.AddItem(Loc.GetString("signboard-font-round"), 2);
        FontOption.SelectId(0);
        FontOption.OnItemSelected += args =>
        {
            FontOption.SelectId(args.Id);
            SyncPendingText();
        };

        FontSize1.OnPressed += _ => SetFontScale(1);
        FontSize2.OnPressed += _ => SetFontScale(2);
        FontSize3.OnPressed += _ => SetFontScale(3);

        TextEdit.OnTextChanged += _ => SyncPendingText();
        StampTextButton.OnPressed += args =>
        {
            if (!_canEdit)
                return;

            if (args.Button.Pressed)
            {
                if (string.IsNullOrWhiteSpace(TextEdit.Text))
                {
                    args.Button.Pressed = false;
                    return;
                }

                SetTool(SignboardTool.Text);
                SyncPendingText();
            }
            else if (DrawArea.Tool == SignboardTool.Text)
            {
                SetTool(SignboardTool.Brush);
            }
        };
        SaveButton.OnPressed += _ => FlushFrames();
        TextPlaceHint.Visible = false;
    }

    public void PopulateStyles(IEnumerable<SignboardFramePrototype> styles)
    {
        StyleOption.Clear();
        _styleIds.Clear();
        StyleOption.AddItem(Loc.GetString("signboard-style-none"), 0);
        _styleIds.Add(NoStyleId);

        var i = 1;
        foreach (var style in styles)
        {
            StyleOption.AddItem(Loc.GetString(style.Name), i);
            _styleIds.Add(style.ID);
            i++;
        }

        StyleOption.SelectId(0);
    }

    public void UpdateState(SignboardBoundUserInterfaceState state)
    {
        _canEdit = state.CanEdit;
        DrawArea.ReadOnly = !state.CanEdit;

        var needsReload = !_pixelsLoaded
                          || (!_dirty && (state.Size != _loadedSize
                                          || state.GridWidth != _loadedGridW
                                          || state.GridHeight != _loadedGridH
                                          || state.Frames.Count != _loadedFrameCount));

        if (needsReload)
        {
            DrawArea.LoadFromState(state.Size, state.GridWidth, state.GridHeight, state.Frames, state.ActiveEditFrame);
            DrawArea.OnionSkin = OnionCheck.Pressed;
            _pixelsLoaded = true;
            _dirty = false;
            _loadedSize = state.Size;
            _loadedGridW = state.GridWidth;
            _loadedGridH = state.GridHeight;
            _loadedFrameCount = state.Frames.Count;
            RebuildFrameOption();
        }

        SetResolutionButtons(state.Size);

        _updatingUi = true;
        // Don't yank the delay slider while the user is still adjusting it.
        if (_pendingDelay == null)
        {
            DelaySlider.Value = state.FrameDelay;
            DelayValueLabel.Text = $"{state.FrameDelay:0.00}s";
        }
        NeonCheck.Pressed = state.Neon;
        PlayingCheck.Pressed = state.Playing;
        PoweredCheck.Pressed = state.Powered;
        _updatingUi = false;

        if (state.FrameStyleId != null)
        {
            var idx = _styleIds.IndexOf(state.FrameStyleId);
            if (idx >= 0)
                StyleOption.SelectId(idx);
        }

        SetEditEnabled(state.CanEdit);
        StatusLabel.Text = Loc.GetString("signboard-status",
            ("size", state.Size),
            ("panels", state.GridWidth * state.GridHeight),
            ("width", state.GridWidth),
            ("height", state.GridHeight),
            ("frame", state.PlaybackFrame + 1),
            ("frames", state.Frames.Count));
    }

    public void FlushFrames()
    {
        CommitPendingDelay();
        if (!_canEdit || !_dirty)
            return;

        _dirty = false;
        OnFramesChanged?.Invoke(DrawArea.ExportFrames(), DrawArea.ActiveFrame);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_pendingDelay == null)
            return;

        _delayCommitTimer -= args.DeltaSeconds;
        if (_delayCommitTimer > 0f)
            return;

        CommitPendingDelay();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            CommitPendingDelay();
            FlushFrames();
        }
        base.Dispose(disposing);
    }

    private void CommitPendingDelay()
    {
        if (_pendingDelay is not { } delay)
            return;

        _pendingDelay = null;
        _delayCommitTimer = 0f;
        OnDelayChanged?.Invoke(delay);
    }

    private void SyncPendingText()
    {
        DrawArea.PendingText = TextEdit.Text;
        DrawArea.TextFontStyle = FontOption.SelectedId;
        DrawArea.TextScale = _fontScale;
        TextPlaceHint.Visible = DrawArea.Tool == SignboardTool.Text && !string.IsNullOrWhiteSpace(TextEdit.Text);
    }

    private void RebuildFrameOption()
    {
        FrameOption.Clear();
        var names = DrawArea.GetFrameNames();
        for (var i = 0; i < names.Count; i++)
            FrameOption.AddItem($"{i + 1}. {names[i]}", i);
        FrameOption.SelectId(DrawArea.ActiveFrame);
    }

    private void SetTool(SignboardTool tool)
    {
        DrawArea.Tool = tool;
        BrushButton.Pressed = tool == SignboardTool.Brush;
        EraserButton.Pressed = tool == SignboardTool.Eraser;
        FillButton.Pressed = tool == SignboardTool.Fill;
        EyedropperButton.Pressed = tool == SignboardTool.Eyedropper;
        StampTextButton.Pressed = tool == SignboardTool.Text;
        SyncPendingText();
    }

    private void SetBrushSize(int size, bool syncSlider = true)
    {
        size = Math.Clamp(size, MinBrushSize, MaxBrushSize);
        DrawArea.BrushSize = size;

        _updatingUi = true;
        if (syncSlider)
            BrushSizeSlider.Value = size;
        BrushSizeEdit.Text = size.ToString();
        _updatingUi = false;
    }

    private void ApplyBrushSizeFromEdit()
    {
        if (!int.TryParse(BrushSizeEdit.Text, out var size))
        {
            BrushSizeEdit.Text = DrawArea.BrushSize.ToString();
            return;
        }

        SetBrushSize(size);
    }

    private void SetFontScale(int scale)
    {
        _fontScale = scale;
        FontSize1.Pressed = scale == 1;
        FontSize2.Pressed = scale == 2;
        FontSize3.Pressed = scale == 3;
        SyncPendingText();
    }

    private void RequestSize(int size)
    {
        FlushFrames();
        OnSizeChanged?.Invoke(size);
    }

    private void SetResolutionButtons(int size)
    {
        Res64Button.Pressed = size == 64;
        Res128Button.Pressed = size == 128;
        Res256Button.Pressed = size == 256;
    }

    private void SetEditEnabled(bool canEdit)
    {
        SaveButton.Disabled = !canEdit;
        AddFrameButton.Disabled = !canEdit;
        RemoveFrameButton.Disabled = !canEdit;
        CopyPrevButton.Disabled = !canEdit;
        StampTextButton.Disabled = !canEdit;
        ApplyStyleButton.Disabled = !canEdit;
        BrushButton.Disabled = !canEdit;
        EraserButton.Disabled = !canEdit;
        FillButton.Disabled = !canEdit;
        EyedropperButton.Disabled = !canEdit;
        BrushSizeSlider.Disabled = !canEdit;
        BrushSizeEdit.Editable = canEdit;
        Res64Button.Disabled = !canEdit;
        Res128Button.Disabled = !canEdit;
        Res256Button.Disabled = !canEdit;
        ColorPicker.Visible = canEdit;
    }
}
